name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src # make sure Python can import from src/

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check uv
        run: uv --version

      - name: Sync deps
        run: uv sync

      - name: Lint / Typecheck / Test
        run: |
          uv run ruff check src tests
          uv run black --check src tests
          uv run mypy src tests
          uv run pytest -q --cov=src
